unit jajmod;

interface

const
  TAK = true;
  NIE = false;

var
  wysokosc:Longint;  { tu b©dzie zapisana wysoko˜† drapacza, jaki mamy
                       do dyspozycji podczas eksperymentu }

  jajka:Integer;     { tu b©dzie zapisana liczba jajek dost©pnych podczas
                       eksperymentu }

  pietro:Longint;    { tu funkcja daj_pytanie powinna umieszcza† numer
                       pi©tra, z kt¢rego ma by† zrzucone jajko }

  odpowiedz:Boolean; { tu b©dzie odpowied« na pytanie, czy zrzucone
                       jajko rozbiˆo si© }

  wiem:Boolean;      { tu nale¾y wpisa† TAK, je˜li wiem jaka jest
                       wytrzymaˆo˜† jajka; w przeciwnym razie warto˜ci¥
                       tej zmiennej powinno by† NIE }

  x:Longint;         { je˜li wiem = TAK, to tu nale¾y wpisa†
                       wytrzymaˆo˜† jajka }


implementation

begin
end.
